name: tests

on:
  push:
    branches:
      - master
      - develop

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.14.1'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        if: github.ref == 'refs/heads/master'
        run: npm run test:cov

      - name: Run tests
        if: github.ref != 'refs/heads/master'
        run: npm test
